### ISSUE TITLE
Xcode crashes

### ISSUE THREAD

**Issue by skywinder** [kohtenko/KOConstraintClean#1]
Hi. I got message right after running script:

![screen shot 2015-07-13 at 09 41 52](https://cloud.githubusercontent.com/assets/3356474/8643991/7de76e56-2943-11e5-8640-9455a7be8730.png)

Then Xcode crashes without any changes in file.

I just wondering, that it could caused by empty lines, that your script leaves in files, instead of constraints:

![screen shot 2015-07-13 at 09 44 26](https://cloud.githubusercontent.com/assets/3356474/8644005/c6d2818c-2943-11e5-997e-8c958ca6b80f.png)

Another wondering - probably it caused by leaving empty node (if there is only only one excluded constraint was in that node)

I can provide you this storyboard for debugging upon request.

p.s. thats for sharing it on habr :wink:

**Comment by kohtenko** [comment]
Your storyboard file would be 100% useful for debbuging. If you don't have any sensitive information in it, please send it to me on kohtenko@gmail.com. 
The reason I suggest crashes your xcode is that your constraint was't removed completely, but was removed from `excluded` section. This could probably return constraint to list of `active` constraints and for some reason create inconsistency.

**Comment by kohtenko** [comment]
This fixed in `1.0.4` version. The reason was you completely excluded constraints still have IBOutlets. 
Moreover, your `storyboard` file contains excluded from display variations only, such as this one:
![](https://dl.dropboxusercontent.com/u/39079341/github.png)
This constraint becomes removed only for several screens, so I would recommend you to check your `storyboard` file with each variation. I 100% sure you'll find your interface broken for some of them.

**Comment by skywinder** [comment]
@kohtenko Awesome, thanks! :+1: 
Yep, the storyboard is really wierd.
It's work fine, because it has separate views for ipad and iphone.
But someone started to build constrains for iPad not in "wany hany" size class. And now it's too late to migrate it to original size class. 
Thanks for quick fix!
